apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    version: "1.2"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: cfahrni/rancher-demo
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
