apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo db migration; sleep 10"]
      restartPolicy: OnFailure
