apiVersion: batch/v1
kind: Job
metadata:
  name: disable-maintenance-page
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: disable-maintenance-page
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo disable maintenance page; sleep 10"]
      restartPolicy: OnFailure
