apiVersion: batch/v1
kind: Job
metadata:
  name: enable-maintenance-page
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: enable-maintenance-page
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo enable maintenance page; sleep 10"]
      restartPolicy: OnFailure
