kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: demoapp
spec:
  rules:
    - host: cluster-public-ip.nip.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: demoapp
              port:
                number: 8080
